#!/bin/bash
OS_NAME=$(uname)
BACK_FILE=
if [ $OS_NAME == "Darwin" ]; then
    BACK_FILE=".bak"
fi
echo "Current os: $OS_NAME, Back file: $BACK_FILE"
PRJ_ROOT_DIR=$(pwd)
PRJ_NAME=$(basename ${PRJ_ROOT_DIR})
TEMP_DIR=${PRJ_ROOT_DIR}/node_modules/@icedeer/rdf4node/templates

echo "<<< Initializing project >>>"
# Step 1: Modify app root 
cp "${TEMP_DIR}/build/Dockerfile" .
sed -i $BACK_FILE "s/\=rdf4node/\=${PRJ_NAME}/g" Dockerfile

cp "${TEMP_DIR}/build/.dockerignore" .
cp "${TEMP_DIR}/build/standalone.json" .
sed -i $BACK_FILE "s/rdf4node/${PRJ_NAME}/g" standalone.json

# Modify app.js
cp -f "${TEMP_DIR}/app.js" .
sed -i $BACK_FILE "s/rdf4node-app/${PRJ_NAME}-app/g" app.js

rm -f *.bak
echo "Project root modified."

# Step 2: Upgrade bin folder
cd bin
cp "${TEMP_DIR}/build/docker-dist" .
sed -i $BACK_FILE "s/rdf4node/${PRJ_NAME}/g" docker-dist

cp "${TEMP_DIR}/bin/www" .
sed -i $BACK_FILE "s/rdf4node:/${PRJ_NAME}:/g" www

rm -f *.bak
cd ..
echo "Folder bin upgraded."

# Step 3: Add common folder
mkdir -p common
cd common
cp "${TEMP_DIR}/common/pubdefs.js" .
cp "${TEMP_DIR}/common/app-events.js" .
cd ..
echo "Folder common created."

# Step 4: Add conf.d folder
mkdir -p conf.d
cd conf.d
cp "${TEMP_DIR}/conf.d/conf.template.js" .
cp "${TEMP_DIR}/conf.d/app.dev.js" .
cp "${TEMP_DIR}/conf.d/version.json" ./version.json
sed -i $BACK_FILE "s/rdf4node/${PRJ_NAME}/g" version.json

rm -f *.bak
cd ..
echo "Folder conf.d created."

# Step 5: Add extensions folder
mkdir -p extensions
echo "Folder extensions created."

# Step 6: Add data models folder
mkdir -p models
cd models
cp "${TEMP_DIR}/models/user.js" .
cd ..
echo "Folder models created."

# Step 7: Add controllers folder
mkdir -p controllers
cd controllers
cp "${TEMP_DIR}/controllers/users.js" .
cd ..
echo "Folder controllers created."

# Step 8: Add middlewares folder
mkdir -p endpoints
cd endpoints
cp "${TEMP_DIR}/endpoints/middlewares.express.js" .
cd ..
echo "Folder endpoints created."

# Step 9: Add services folder
mkdir -p services
cd services
cp "${TEMP_DIR}/services/user.js" .
cd ..
echo "Folder services created."

# Step 10: Add daemons folder
mkdir -p daemons
echo "Folder daemons created."

# Step 11: Modify routes
cd routes
rm -f users.js
cp -f "${TEMP_DIR}/routes/monitor.js" .
mkdir -p v1
cd v1
cp "${TEMP_DIR}/routes/v1/users.js" .
cp "${TEMP_DIR}/routes/v1/logdir.js" .
cd ..
cd ..
echo "Folder routes modified."

# Step 12: Copy views
cd views
cp -f "${TEMP_DIR}/views/api.ejs" .
cd ..
echo "Folder views modified."

# Step 13: Create application entry
mkdir -p applications
echo "Folder applications created."

echo "Install addtional libs: mongoose@7 redis ..."
npm install mongoose@7 redis --save --no-audit

echo "<<< Congratulations!!! >>>"
echo "Please run command to start: npm run start"