/**
 * Created by eric on 3/30/16.
 */

// Define wings public return codes
const eRetCodes = {
    OP_FAILED: -1,
    // ========== NOTIFICATION
    CONTINUE: 100,
    SWITCH_PROTOCOL: 101,
    // ========== SUCCESS
    OK: 200,
    SUCCESS: 200,
    CREATED: 201,
    ACCEPTED: 202,
    NON_AUTH_INFO: 203,
    NO_CONTENT: 204,
    RESET_CONTENT: 205,
    PARTIAL_CONTENT: 206,
    // customized
    ALREADY_EXIST: 210,

    // ========== REDIRECT
    MULTIPLE_CHOICE: 300,
    MOVED_PERMANENTLY: 301,
    FOUND: 302,
    SEE_OTHER: 303,
    NOT_MODIFIED: 304,
    USE_PROXY: 305,
    UNUSED: 306,
    TEMP_REDIRECT: 307,
    PERMANENT_REDIRECT: 308,
    // ========== CLIENT ERROR
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    PAYMENT_REQUIRED: 402,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    METHOD_NOT_ALLOWED: 405,
    NOT_ACCEPTABLE: 406,
    PROXY_AUTH_REQUIRED: 407,
    REQUEST_TIMEOUT: 408,
    CONFLICT: 409,
    GONE: 410,
    LENGTH_REQUIRED: 411,
    PRECONDITION_FAILED: 412,
    REQUEST_ENTITY_TOO_LARGE: 413,
    REQUEST_URI_TOO_LONG: 414,
    UNSUPPORTED_MEDIA_TYPE: 415,
    RANGE_NOT_SATISFIABLE: 416,
    EXPECTATION_FAILED: 417,
    SESSION_EXPIRED: 420,
    // customized
    INVALID_SIGNATURE: 430,
    INVALID_MOBILE: 431,
    PARAMETER_MISSING: 440,
    INVALID_ACC_TOKEN: 441,
    INVALID_ACCOUNT_STATE: 442,
    INVALID_INVT_CODE: 443,
    INSUFFICIENT_BALANCE: 444,
    INVALID_PACKAGE: 445,
    RELOGIN_REQUIRED: 446,
    // ========== SERVER ERROR
    INTERNAL_SERVER_ERR: 500,
    IMPLEMENTED: 501,
    BAD_GATEWAY: 502,
    SERVICE_UNAVAILABLE: 503,
    GATEWAY_TIMEOUT: 504,
    HTTP_VER_NOT_SUPPORTED: 505,
    RECHARGE_SERVER_ERR: 506,
    GATEWAY_OUT_SERVICE: 507,
    // DATABASE ERROR
    DB_ERROR: 510,
    DB_CONNECT_ERR: 511,
    DB_QUERY_ERR: 512,
    DB_INSERT_ERR: 513,
    DB_UPDATE_ERR: 514,
    DB_DELETE_ERR: 515,
    // REDIS ERRORs
    REDIS_ERR: 600,
    REDIS_CONN_ERR: 601,
    REDIS_METHOD_NOTEXISTS: 602,
    REDIS_METHOD_TOOMANYPARAMS: 603,
    REDIS_BAD_REQUEST: 604,
    // TEDIOUS ERRORs
    TEDIOUS_ERROR: 1433
};

if (typeof module !== 'undefined' && typeof module.exports != 'undefined') {
    module.exports = eRetCodes;
}
